version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    container_name: resume-converter
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - GEMINI_API_KEY=GEMINI_API_KEY
